### PR TITLE
feat: Provide option of in-memory datastore

### PR DESCRIPTION
**Pull request by forrcaho**
…tabase store

Fixes issue #27 

I ended up using the package name 'datastore' to avoid conflicts with the variable name 'store' I wanted to use for it in api.go. That's also the name of the command-line switch, which currently accepts two values: 'pg' for postgres or 'memory' for the in-memory datastore.

I also fixed a bug that the Location header wasn't getting printed out when a new game was requested using the api.

### CODE REVIEW

**Comment by forrcaho** [comment]
CircleCI seems to have some problem with directory renaming, as it's complaining about the directory I renamed. It's obviously there, as you can see from the diffs -- and of course, I tested my code before making the pull request and am sure it works.

**Comment by mauricioabreu** [comment]
Amazing job!!! :+1: 
You implemented the in-memory repository and also fixed a bug (good catch!).

CircleCI is misconfigured. I pushed a new commit to master branch. It will probably be solved after rebasing/merging with master.

**Comment by forrcaho** [comment]
In my local environment, I had to put a symlink from `~/go/src/go-hangman` to `~/go/src/github.com/mauricioabreu/go-hangman` in order for Go to see the other modules inside the package. Without that link, `dep` will put a version in `vendor`. I think this is what happened in CircleCI -- it loaded the latest _committed_ version of the repo into `vendor` where `datastore` wasn't present.

**Comment by mauricioabreu** [comment]
I think it happens because in the beginning all imports were not correct.
Go's importing system is a bit...hard. After changing to `github.com/mauricioabreu/go-hangman`, every package imported started to fail for new contributors because they did not have the `go/src/go-hanmang` there.

**Pull request merged**
