### PR TITLE
feat: Better JSON representantion for used letters

### PR DESCRIPTION
**Pull request by mauricioabreu**
## Proposed changes

Before the representation looked like:

```
"used": [
    "d": "true",
    "z": "true"
],
```

Now the representation looks like:
```
"used": [
    "d",
    "z"
],
```

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/mauricioabreu/go-hangman/blob/master/CONTRIBUTING.md) doc
- [x] Lint and unit tests pass locally with my changes (if appropriate)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by mauricioabreu** [comment]
@forrcaho what do you think about this solution? :)

It looks more simple than using a custom marshaller.

**Comment by forrcaho** [comment]
That works, but I don't know why you want to make it a `[]string` instead of just a `string`. I already added the function `mapToString` to `db/store.go` which would make it a plain string (and _does_ for the database record). But either way works fine -- whatever you decide.

**Comment by mauricioabreu** [comment]
I think I am more inclined to use an array because the meaning of the word `used` on this context.
`What are the used letters so far?` and then we answer with a collection, not a "word". Does it make sense?

I am not sure if it is better for clients to read a string or a collection (`clients` I mean a browser reading the API)

**Comment by forrcaho** [comment]
Sure, that makes sense. I was wondering earlier about the Game structure attribute 'Letters' which seems misnamed for this very reason. I think maybe that should be 'Word' or 'Answer' or something like that ... "Letters" sounds to me like a collection, not a word.

**Comment by mauricioabreu** [comment]
I must confess I am confused now. I was wondering what is the appropriate way to represent the `letters` (word) and `used` to users/clients.

```
{
    "word": [
        "s",
        "u",
        "g",
        "a",
        "_",
        "-",
        "f",
        "_",
        "e",
        "e"
    ],
    "used": [
        "s",
        "u",
        "g",
        "a",
        "f",
        "e"
    ]
}
```

or

```
{
    "word": "suga_-f_ee",
    "used": "sugafe"
}
```

?

**Comment by forrcaho** [comment]
I don't they need to have the same representation, because they're different things: _word_ must appear in order and can have duplicate letters (or placeholder underscores), whereas _used_ does not have an order associated with it and cannot have duplicates.

I'd use a string for "word" in any case, and although I'd just as soon have a string for "used", that's just because I'm an old C coder who still thinks of strings and char arrays as being the same thing. Your reason for using an array for "used" makes sense.

**Comment by mauricioabreu** [comment]
Agreed @forrcaho 

I will open a new PR making these changes. Thank you!

**Pull request merged**
