### PR TITLE
support words with dashes, spaces, and apostrophies

### PR DESCRIPTION
**Pull request by jrwren**
https://github.com/mauricioabreu/go-hangman/issues/10

### CODE REVIEW

**Comment by mauricioabreu** [comment]
Hey @jrwren 
Thank you for your contribution :heart: 

It is going good! I think there are some things missing. Sorry for not describing it in the issue. Not it is there: https://github.com/mauricioabreu/go-hangman/issues/10

> How it should be:
> 
> It must accept dashes, spaces and apostrophes
> The game can't count it as letters. Only a-z characters must count as guesses. Example: if the word is sugar-free, user will not need to guess the dash (hyphen).
> It should always be "revealed"

**Comment by jrwren** [comment]
Yes, that is how this is implemented.

The dashes, spaces, and apostrophes are "free". The `RevealWord` function will always reveal those free characters.

e.g. `sugar-free` will be displayed as `_____-____` at the start of the game.

Am I misunderstanding the requirements?

**Comment by mauricioabreu** [comment]
@jrwren this part of the feature works but the user should not need to enter the dash in sugar-free to win the game.

Example:

1 - Revealed word: sugar-f_ee
2 - Now the user enters "r"
3 - Revealed word: sugar-free
4 - WIN!

What is currently happening is that the user needs to enter the dash "-" to win

**Comment by mauricioabreu** [comment]
I think a good approach here is to change the part of the code it creates the `letters` array (the set of letters the word to be guesses has).

**Comment by mauricioabreu** [comment]
@jrwren what is your opinion? If needed, you can refactor the code or do whatever needed to help you to accomplish this feature. I am here to help! :+1:

**Comment by jrwren** [comment]
Oh, thanks. I understand now and I will update the PR

**Comment by jrwren** [comment]
> I think a good approach here is to change the part of the code it creates the `letters` array (the set of letters the word to be guesses has).

Oops, I hadn't read this reply and I implemented a different way. Let me know if you'd like me to change.

**Comment by mauricioabreu** [comment]
@jrwren It works and you made a very good test. :clap: 

Thank you sooo much!

**Pull request merged**
